#!/bin/bash

#making directory public_html and file readme.txt
mkdir public_html
cd public_html
touch readme.txt
chmod 777 readme.txt
cd ..

#fetching files in the directory
file_list=( $(ls -p | grep -v /) )

#copying first four of them
for index in 0 1 2 3
 do
  cp ${file_list[$index]} ./public_html
 done

#entering the dirctory
cd public_html

#copying the files 
mkdir public_html
find ./ -type f -exec cp {} ./public_html \;

#renaming the copied public_html
mv ./public_html RENAMED_public_html
