#!/bin/bash
# script will write the output in file 'Assignment.log'


echo -e "\n\nOUTPUT:\nDATE:"`date`"\n" >> Assignment.log 2>&1
echo -e "\nYour Hostname is:\t"`hostname` >> Assignment.log 2>&1
echo -e "OS with version:\t"`uname -s -r` >> Assignment.log 2>&1
echo -e "path of home directory:\t"$HOME >> Assignment.log 2>&1
echo -e "Users logged in:\t"`users` >> Assignment.log 2>&1
echo -e "Your Groups are:\t["`groups`"]" >> Assignment.log 2>&1

# grabbing list of files in present and sub directories
file_list=( $(ls -pR $HOME| grep -v /) )

# printing elements line by line in file 
echo -e "List of files in home and subdirectories:\n" >> Assignment.log 2>&1
printf -- '%s\n' "${file_list[@]}" >> Assignment.log 2>&1

#displaying completion message
echo "Script executed Successfully! OUTPUT stored in file: Assignment.log"
